/// Description
Class BO.Reservation Extends EnsLib.SOAP.Service
{
    
/*Parameter SERVICENAME = "ServiceVoitureSoap";
Parameter ADAPTER;

Method CommanderVoiture(marque As %String, modele As %String, couleur As %String) As msg.commandeVoitureRpse [ WebMethod ]
{
    set pOutput = ##class(msg.commandeVoitureRpse).%New()
    
s


/*
    set tsc = ..SendRequestSync("CommandeVoiture",msg,.pOutput)
    Quit pOutput


*/

}
